server:
  port: 8484
spring.application.name : payment
spring.json:

spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      spring.json.trusted.packages: "*"

  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



logging:
  level:
    root : debug
    org.springframework.web : info
